version: '3'

services:
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: full-cycle-mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: rodrigorrch/nginx-full-cycle:latest
    container_name: full-cycle-nginx
    networks:
      - fullcycle_network
    ports:
      - 8080:80
    depends_on:
      - node

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: rodrigorrch/node-full-cycle:latest
    container_name: full-cycle-node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
    networks:
      - fullcycle_network
    tty: true
    depends_on:
      - mysql

networks:
  fullcycle_network:
    driver: bridge